networks:
  php_pro:
    driver: bridge

volumes:
  mysql_volume:
    driver: local

services:
  app:
    build:
      context: .docker/php
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    networks:
      - php_pro
  database:
    image: "mysql:8"
    restart: always
    ports:
      - "33061:3306"
    volumes:
      - "mysql_volume:/var/lib/mysql"
    environment:
      MYSQL_USER: amantem
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: php_homework
    networks:
      - php_pro
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - php_pro